import { jest } from '@jest/globals';
import fs from 'fs-extra';
import path from 'path';
import os from 'os';
import {
  detectAICode,
  analyzeQuality,
  analyzeSecurity,
  extractFunctions,
  analyzeFile,
  outputResults,
} from '../commands/analyze.js';

// Real-module tests (replaced previous suite that tested self-defined fixtures)
describe('analyze command — real detectors', () => {
  describe('detectAICode', () => {
    test('detects auto-generated markers', () => {
      const r = detectAICode('// This file was generated by tool X\ncode();', ['// This file was generated by tool X', 'code();']);
      expect(r.detected).toBe(true);
      expect(r.indicators.length).toBeGreaterThan(0);
    });

    test('clean simple code reports zero duplicates', () => {
      const lines = ['const a = 1;', 'const b = 2;', 'const c = 3;'];
      const r = detectAICode(lines.join('\n'), lines);
      expect(r.detected).toBe(false);
      expect(r.duplicateRatio).toBe(0);
    });

    test('detects repeated lines', () => {
      const lines = ['doStuff();', 'doStuff();', 'doStuff();', 'doOther();'];
      const r = detectAICode(lines.join('\n'), lines);
      expect(r.duplicateRatio).toBeGreaterThan(0.1);
      expect(r.indicators.some(i => i.includes('重复代码'))).toBe(true);
    });

    test('empty or comment-only file: duplicateRatio is 0, not NaN (bugfix)', () => {
      const r1 = detectAICode('', []);
      expect(r1.duplicateRatio).toBe(0);
      expect(Number.isNaN(r1.duplicateRatio)).toBe(false);
      const r2 = detectAICode('// only a comment', ['// only a comment']);
      expect(r2.duplicateRatio).toBe(0);
      expect(Number.isNaN(r2.duplicateRatio)).toBe(false);
    });
  });

  describe('analyzeQuality', () => {
    const clean = ['function add(a, b) {', '  return a + b;', '}', 'const x = add(1, 2);'];

    test('clean short file scores 100 with no issues', () => {
      const r = analyzeQuality(clean.join('\n'), clean, '.js');
      expect(r.score).toBe(100);
      expect(r.issues).toHaveLength(0);
      expect(r.metrics.functionCount).toBe(1);
    });

    test('long lines are flagged as style warning and reduce score by 10', () => {
      const lines = ['const x = "' + 'a'.repeat(200) + '";'];
      const r = analyzeQuality(lines.join('\n'), lines, '.js');
      expect(r.issues.some(i => i.type === 'style' && i.severity === 'warning')).toBe(true);
      expect(r.score).toBe(90);
    });

    test('TODOs are reported as info severity (no score penalty)', () => {
      const lines = ['const a = 1; // TODO: implement', 'const b = 2; // FIXME: broken'];
      const r = analyzeQuality(lines.join('\n'), lines, '.js');
      const todo = r.issues.find(i => i.type === 'todos');
      expect(todo.severity).toBe('info');
      expect(r.score).toBe(100);
    });
  });

  describe('analyzeSecurity', () => {
    test('clean code is secure', () => {
      const r = analyzeSecurity('const x = compute();', '.js');
      expect(r.secure).toBe(true);
      expect(r.vulnerabilities).toHaveLength(0);
    });

    test('eval marks file insecure with high severity', () => {
      const r = analyzeSecurity('eval(userInput);', '.js');
      expect(r.secure).toBe(false);
      expect(r.vulnerabilities[0].severity).toBe('high');
    });

    test('hardcoded password is high severity', () => {
      const r = analyzeSecurity("const password = 'hunter2';", '.js');
      expect(r.secure).toBe(false);
      expect(r.vulnerabilities[0].severity).toBe('high');
    });

    test('counts EVERY occurrence, not just the first (g-flag bugfix)', () => {
      const r = analyzeSecurity(
        "const password = 'a';\nconst password = 'b';\nconst password = 'c';",
        '.js'
      );
      const pw = r.vulnerabilities.find(v => v.type.includes('硬编码密码'));
      expect(pw.count).toBe(3);
    });

    test('multiple distinct vulnerabilities all reported', () => {
      const r = analyzeSecurity(
        "const apiKey = 'sk-123';\ndiv.innerHTML = userInput;\nconst secret = 'x';",
        '.js'
      );
      expect(r.vulnerabilities).toHaveLength(3);
      expect(r.secure).toBe(false); // api_key + secret are high
    });
  });

  describe('extractFunctions', () => {
    test('finds function declarations and arrow functions with 1-based lines', () => {
      const content = [
        "import x from 'y';",
        'function alpha() {',
        '  return 1;',
        '}',
        'const beta = async (a) => a;',
        'const gamma = (b) => b;',
      ].join('\n');
      const fns = extractFunctions(content);
      const names = fns.map(f => f.name);
      expect(names).toContain('alpha');
      expect(names).toContain('beta');
      expect(fns.find(f => f.name === 'alpha').line).toBe(2);
      expect(fns.find(f => f.name === 'beta').line).toBe(5);
    });

    test('returns empty array for plain prose', () => {
      expect(extractFunctions('just some text\nno functions here')).toEqual([]);
    });
  });

  describe('analyzeFile (end-to-end on tmp fixture)', () => {
    let tmp;
    beforeAll(async () => {
      tmp = path.join(os.tmpdir(), `aid-analyze-test-${Date.now()}`);
      await fs.ensureDir(tmp);
    });
    afterAll(async () => { await fs.remove(tmp); });

    test('full options produce every report section', async () => {
      const file = path.join(tmp, 'sample.js');
      await fs.writeFile(file, [
        'function add(a, b) {',
        '  return a + b;',
        '}',
        "const password = 'leak';",
      ].join('\n'));
      const r = await analyzeFile(file, { checkAi: true, quality: true, security: true });
      expect(r.file).toBe(file);
      expect(r.lines).toBe(4);
      expect(r.metrics.codeLines).toBe(4);
      expect(r.aiIndicators).toBeDefined();
      expect(r.quality).toBeDefined();
      expect(r.security.secure).toBe(false);
      expect(r.functions.map(f => f.name)).toContain('add');
    });
  });

  describe('outputResults — text mode', () => {
    test('single-file result is no longer silent; security findings rendered (bugfix)', async () => {
      const spy = jest.spyOn(console, 'log').mockImplementation(() => {});
      try {
        const single = {
          file: 'vuln.js',
          lines: 3,
          metrics: { codeLines: 3, commentLines: 0, blankLines: 0 },
          security: {
            secure: false,
            vulnerabilities: [{ type: 'eval() 使用 - 潜在代码注入风险', severity: 'high', count: 2 }],
          },
        };
        await outputResults(single, {});
        const text = spy.mock.calls.flat().join('\n');
        expect(text).toContain('vuln.js');
        expect(text).toContain('eval() 使用');
        expect(text).toContain('high');
      } finally {
        spy.mockRestore();
      }
    });

    test('secure single file shows ✓ line', async () => {
      const spy = jest.spyOn(console, 'log').mockImplementation(() => {});
      try {
        await outputResults({ file: 'ok.js', lines: 2, metrics: {}, security: { secure: true, vulnerabilities: [] } }, {});
        const text = spy.mock.calls.flat().join('\n');
        expect(text).toContain('无高危问题');
      } finally {
        spy.mockRestore();
      }
    });
  });
});
